### PR TITLE
change jade to pug

### PR DESCRIPTION
**Pull request by demsking**

### CODE REVIEW

**Comment by wolfgang42** [comment]
I think `*.jade` should also be highlighted, for backward compatibility. There's still going to be .jade files around for a while, until everything gets renamed.

**Comment by RangerMauve** [comment]
Would it make sense to get rid of the `jade.xml` file and add `*.jade` to the `pug.xml` file, then?

**Comment by demsking** [comment]
Like `extensions="*.pug,*.jade"`?

**Comment by RangerMauve** [comment]
Yeah, that should do it.

**Comment by demsking** [comment]
Changed

**Comment by RangerMauve** [comment]
Perfect, thanks! Should the repo be renamed, too?

**Pull request merged**
